AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false


Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/RescueModifier:
  Enabled: false
